db.exercise.ensureIndex({creationDate: 1});
db.exercise.ensureIndex({creationDate: -1, lastModifiedDate: -1});
db.exercise.ensureIndex({lastModifiedDate: -1, creationDate: -1});
db.exercise.ensureIndex({lastModifiedDate: 1});
db.exercise.ensureIndex({user: 1}) ;
db.exercise.ensureIndex({sport: 1});
db.exercise.ensureIndex({duration: 1}) ;
db.exercise.ensureIndex({distance : 1});
db.exercise.ensureIndex({tags: 1});
db.groups.ensureIndex({name: 1});
db.groups.ensureIndex({users: 1});
db.nccache.ensureIndex({u: 1});