(ns ontrail.nlp
  (:import [org.tartarus.snowball.ext finnishStemmer]))

(defn stem [word]
  (if (and word (> (count word) 0))
    (let [stemmer (finnishStemmer.)]
      (.setCurrent stemmer word)
      (.stem stemmer)
      (.getCurrent stemmer))
    ""))

(def verb-map {"Beach volley"       "pelasi biitsiä"
               "Crossfit"           "crossfittasi"
               "Cyclocross"         "cyclocrossaili"
               "Crosstrainer"       "tyllerövispilöi"
               "Frisbeegolf"        "frisbeegolffasi"
               "Golf"               "golffasi"
               "Hieronta"           "oli hierottavana"
               "Hiihto"             "hiihti"
               "Jalkapallo"         "jalkapalloili"
               "Jooga"              "joogasi"
               "Jumppa"             "jumppasi"
               "Juoksu"             "juoksi"
               "Jääkiekko"          "jääkiekkoili"
               "Kahvakuula"         "nosti kuulaa"
               "Kamppailulaji"      "kamppaili"
               "Kaukalopallo"       "kaukalopalloili"
               "Kickbike"           "kikkaili"
               "Kiipeily"           "kiipeili"
               "Koripallo"          "koripalloili"
               "Kuntopiiri"         "teki kuntopiiriä"
               "Kuntosali"          "kävi kuntosalilla"
               "Kuntopyörä"         "kuntopyöräili"
               "Kävely"             "käveli"
               "Laskettelu"         "lasketteli"
               "Lentopallo"         "lentopalloili"
               "Leuanveto"          "veti leukoja"
               "Luistelu"           "luisteli"
               "Luisteluhiihto"     "luisteluhiihti"
               "Lumikenkäily"       "lumikenkäili"
               "Lumilautailu"       "lumilautaili"
               "Maantiepyöräily"    "maantiepyöräili"
               "Maastojuoksu"       "juoksi maastossa"
               "Maastopyöräily"     "pyöräili maastossa"
               "Melonta"            "meloi"
               "Muu laji"           "teki jotain muuta"
               "Muu merkintä"       "merkitsi jotain muuta"
               "Nyrkkeily"          "nyrkkeili"
               "Perinteinen hiihto" "hiihti"
               "Pilates"            "harrasti pilatesta"
               "Pumppi"             "pumppasi"
               "Potkukelkkailu"     "potkukelkkaili"
               "Pyöräily"           "pyöräili"
               "Ratsastus"          "ratsasti"
               "Ringette"           "pelasi ringetteä"
               "Rogaining"          "rogainasi"
               "Rullahiihto"        "rullahiihti"
               "Rullaluistelu"      "rullaluisteli"
               "Sairaus"            "sairasti"
               "Sauvakävely"        "sauvakäveli"
               "Seikkailu-urheilu"  "seikkaili"
               "Sisäsoutu"          "souti ergometrillä"
               "Soutu"              "souti"
               "Spinning"           "spinnasi"
               "Squash"             "pelasi squashia"
               "Sulkapallo"         "pelasi sulista"
               "Suunnistus"         "suunnisti"
               "Sähly"              "pelasi sählyä"
               "Salibandy"          "pelasi salibandya"
               "Tanssi"             "tanssi"
               "Tapahtuma"          "loi tapahtuman"
               "Tennis"             "pelasi tennistä"
               "Telinevoimistelu"   "telinevoimisteli"
               "Triathlon"          "ui, pyöräili ja juoksi"
               "Uinti"              "ui"
               "Vaellus"            "vaelsi"
               "Venyttely"          "venytteli"
               "Vesijuoksu"         "vesijuoksi"
               "Yleisurheilu"       "yleisurheili"})

(def sports (sort (keys verb-map)))

(defn get-verb [sport-id]
  (if (string? sport-id)
    (let [verb (verb-map sport-id)]
      (if (= nil verb)
        (str "harrasti lajia " (.toLowerCase sport-id))
        verb))
    "nil-sport-id"))

(def stop-words
  #{"ja" "ei" "oli" "mutta" "on" "kun"
    "että"
    "niin"
    "se"
    "sitten"
    "ihan"
    "vähän"
    "nyt"
    "jälkeen"
    "vielä"
    "kyllä"
    "taas"
    "kanssa"
    "en"
    "jo"
    "nbsp"
    "vaan"
    "aika"
    "tuli"
    "kuin"
    "hyvä"
    "ollut"
    "sen"
    "joten"
    "vaikka"
    "km"
    "olla"
    "meni"
    "ennen"
    "tänään"
    "sitä"
    "hyvin"
    "ole"
    "jos"
    "no"
    "siinä"
    "koko"
    "kuitenkin"
    "eli"
    "tuntui"
    "siis"
    "olin"
    "paljon"
    "myös"
    "tai"
    "oikein"
    "piti"
    "vain"
    "olisi"
    "joka"
    "aikaa"
    "ehkä"
    "mitään"
    "eikä"
    "siitä"
    "voi"
    "mennä"
    "noin"
    "tämä"
    "10"
    "mä"
    "pitää"
    "ne"
    "aina"
    "mitä"
    "mun"
    "muuten"
    "tosi"
    "sain"
    "olen"
    "alkoi"
    "tuo"
    "siellä"
    "varmaan"
    "mukaan"
    "näin"
    "kiva"
    "lähdin"
    "ettei"
    "kai"
    "jopa"}
  )
